# Prometheus alerting rules for AuditHound
groups:
  - name: audithound.alerts
    rules:
      # Service availability alerts
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.instance }} is down"
          description: "Service {{ $labels.instance }} has been down for more than 1 minute."
      
      # High CPU usage
      - alert: HighCPUUsage
        expr: (100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is above 80% for more than 5 minutes on {{ $labels.instance }}"
      
      # High memory usage
      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "Memory usage is above 85% on {{ $labels.instance }}"
      
      # High disk usage
      - alert: HighDiskUsage
        expr: (1 - (node_filesystem_avail_bytes / node_filesystem_size_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High disk usage on {{ $labels.instance }}"
          description: "Disk usage is above 85% on {{ $labels.instance }}"
      
      # API response time alerts
      - alert: HighAPIResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 0.5
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "High API response time"
          description: "95th percentile API response time is above 500ms for more than 3 minutes"
      
      # Database connection alerts
      - alert: DatabaseConnectionsHigh
        expr: pg_stat_activity_count > 80
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High number of database connections"
          description: "Database has more than 80 active connections"
      
      # Redis memory usage
      - alert: RedisMemoryHigh
        expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Redis memory usage is high"
          description: "Redis memory usage is above 90%"
      
      # Failed login attempts
      - alert: HighFailedLogins
        expr: increase(http_requests_total{endpoint="/api/v1/auth/login", status=~"4.."}[5m]) > 10
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High number of failed login attempts"
          description: "More than 10 failed login attempts in the last 5 minutes"
      
      # Error rate alerts
      - alert: HighErrorRate
        expr: (rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m])) * 100 > 5
        for: 3m
        labels:
          severity: critical
        annotations:
          summary: "High error rate"
          description: "Error rate is above 5% for more than 3 minutes"
      
      # Certificate expiration
      - alert: SSLCertificateExpiring
        expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 30
        for: 1h
        labels:
          severity: warning
        annotations:
          summary: "SSL certificate expiring soon"
          description: "SSL certificate for {{ $labels.instance }} expires in less than 30 days"
      
      # Compliance scan failures
      - alert: ComplianceScanFailures
        expr: increase(compliance_scan_failures_total[10m]) > 5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High number of compliance scan failures"
          description: "More than 5 compliance scans have failed in the last 10 minutes"
      
      # AI analytics processing delays
      - alert: AIAnalyticsDelay
        expr: ai_analytics_processing_duration_seconds > 300
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "AI analytics processing is slow"
          description: "AI analytics processing is taking more than 5 minutes"

  - name: audithound.database
    rules:
      # Database performance alerts
      - alert: DatabaseSlowQueries
        expr: pg_stat_statements_mean_time_ms > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Slow database queries detected"
          description: "Average query time is above 1000ms"
      
      # Database deadlocks
      - alert: DatabaseDeadlocks
        expr: increase(pg_stat_database_deadlocks[10m]) > 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Database deadlocks detected"
          description: "Database deadlocks have been detected"
      
      # Database backup failures
      - alert: DatabaseBackupFailure
        expr: time() - database_backup_last_success_timestamp > 86400
        for: 1h
        labels:
          severity: critical
        annotations:
          summary: "Database backup failure"
          description: "Database backup has not succeeded in the last 24 hours"

  - name: audithound.security
    rules:
      # Security alerts
      - alert: SuspiciousActivity
        expr: increase(security_events_total{type="suspicious"}[5m]) > 5
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Suspicious activity detected"
          description: "More than 5 suspicious security events in the last 5 minutes"
      
      # Brute force attacks
      - alert: BruteForceAttack
        expr: increase(failed_login_attempts_total[1m]) > 20
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Potential brute force attack"
          description: "More than 20 failed login attempts from {{ $labels.ip }} in 1 minute"
      
      # Unauthorized access attempts
      - alert: UnauthorizedAccess
        expr: increase(http_requests_total{status="403"}[5m]) > 10
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High number of unauthorized access attempts"
          description: "More than 10 403 errors in the last 5 minutes"

  - name: audithound.business
    rules:
      # Business metric alerts
      - alert: LowComplianceScore
        expr: avg(compliance_score) < 70
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Low compliance score"
          description: "Average compliance score is below 70%"
      
      # High severity findings
      - alert: HighSeverityFindings
        expr: increase(compliance_findings_total{severity="critical"}[30m]) > 10
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High number of critical findings"
          description: "More than 10 critical compliance findings in the last 30 minutes"
      
      # Tenant resource usage
      - alert: TenantResourceExhaustion
        expr: tenant_resource_usage_percent > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Tenant resource usage is high"
          description: "Tenant {{ $labels.tenant_id }} is using more than 90% of allocated resources"